version: "2"

services:
  basic-app-app:
    container_name: "basicApp-app"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "4001:4000"
    depends_on:
      - basic-app-db

  basic-app-db:
    container_name: "basicApp-db"
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysqlInit:/docker-entrypoint-initdb.d
    restart: "always"
